# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Xilinx/Projects/FPGA-based-CBC-encryptor-and-decryptor/FPGA-based-CBC-encryptor-and-decryptor.srcs/sources_1/bd/Dual_B_RAM/ip/Dual_B_RAM_blk_mem_gen_0_0/Dual_B_RAM_blk_mem_gen_0_0.xci
# IP: The module: 'Dual_B_RAM_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Projects/FPGA-based-CBC-encryptor-and-decryptor/FPGA-based-CBC-encryptor-and-decryptor.srcs/sources_1/bd/Dual_B_RAM/ip/Dual_B_RAM_blk_mem_gen_0_0/Dual_B_RAM_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dual_B_RAM_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Xilinx/Projects/FPGA-based-CBC-encryptor-and-decryptor/FPGA-based-CBC-encryptor-and-decryptor.srcs/sources_1/bd/Dual_B_RAM/ip/Dual_B_RAM_blk_mem_gen_0_0/Dual_B_RAM_blk_mem_gen_0_0.xci
# IP: The module: 'Dual_B_RAM_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Projects/FPGA-based-CBC-encryptor-and-decryptor/FPGA-based-CBC-encryptor-and-decryptor.srcs/sources_1/bd/Dual_B_RAM/ip/Dual_B_RAM_blk_mem_gen_0_0/Dual_B_RAM_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dual_B_RAM_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
