# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cypher_system.xdc

# Block Designs: bd/Dual_B_RAM/Dual_B_RAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dual_B_RAM || ORIG_REF_NAME==Dual_B_RAM} -quiet] -quiet

# IP: bd/Dual_B_RAM/ip/Dual_B_RAM_blk_mem_gen_0_0/Dual_B_RAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dual_B_RAM_blk_mem_gen_0_0 || ORIG_REF_NAME==Dual_B_RAM_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/Dual_B_RAM/Dual_B_RAM_ooc.xdc
